### PR TITLE
ASM-6516 Add Nagios support for Emc

### PR DESCRIPTION
**Pull request by rjbalest**
In conjunction with asm-deployer PR with the same Jira ID

### CODE REVIEW

**Comment by rjbalest** [comment]
@logankimmel  This one goes with the other in asm-deployer

**Comment by logankimmel** [comment]
+1.  Requires https://github.com/dell-asm/asm-deployer/pull/1636

**Comment by rjbalest** [comment]
@logankimmel  PR got merged: https://github.com/dell-asm/asm-deployer/commit/b38db3e1bc75a5e4e8e8f017a8a2e8012697a309
Can you merge this one

**Comment by logankimmel** [comment]
@gavin-scott will have to

**Comment by gavin-scott** [comment]
@rjbalest please resolve the jira if appropriate.

**Pull request merged**
